name: Python Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
    - uses: actions/checkout@v3
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        pip install build
    - name: Test API
      run: |
        pylint prismacloud/*/*py
    - name: Test Scripts
      run: |
        python -m build
        pip install dist/prismacloud_api-*
        pylint scripts/*py
